### ISSUE TITLE
未知的模块 构建失败

### ISSUE THREAD

**Issue by purewyh** [zhouyuexie/vue-input-code#1]
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/wyh/www/itCommunity/node_modules/vue-input-code/.babelrc" at 0, attempted to resolve relative to

**Comment by zhouyuexie** [comment]
@purewyh babel需要`transform-runtime`插件,请在你的项目路径输入以下命令:

```
npm install transform-runtime --save-dev
```

**Comment by purewyh** [comment]
@zhouyuexie  这个模块安装过后 还是报上面的那个错误

**Comment by zhouyuexie** [comment]
建议尝试安装以下依赖:

```
"babel-core"
"babel-eslint"
"babel-loader"
"babel-plugin-component"
"babel-plugin-transform-es2015-computed-properties"
"babel-plugin-transform-runtime"
"babel-preset-es2015"
"babel-preset-stage-0"
"babel-runtime"
```

然后删除你的node_modules文件夹重新`npm install`.
