### ISSUE TITLE
type 为 number 时还可以输入空格

### ISSUE THREAD

**Issue by smalike** [zhouyuexie/vue-input-code#13]
type 为 number 时还可以输入空格。
并且希望增加自定义验证码输入格式的方法。

**Comment by zhouyuexie** [comment]
1. 空格bug确实存在，周末修复
2. 自定义验证码输入指的是什么，可以再详细描述一下吗？

**Comment by smalike** [comment]
就如同当前问题一样，可以写对应的方法来验证输入是否合规。

**Comment by zhouyuexie** [comment]
Fixed "can input space" in version 1.5.0

Add `customValidate` for validate user input.
