### ISSUE TITLE
demo中快速输入似乎会跳过某个input,导致某个小input值为空

### ISSUE THREAD

**Issue by artiely** [zhouyuexie/vue-input-code#2]

**Comment by zhouyuexie** [comment]
@artiely 谢谢你的反馈,测试发现能重现这个bug.

我会在近期给出解决方案,解决后我会这里通知你,再次感谢你的支持.🤗

**Comment by zhouyuexie** [comment]
@artiely https://www.npmjs.com/package/vue-input-code

新版本1.3.0已经修复,这是一个事件监听延迟的bug.
