### ISSUE TITLE
在安卓版chrome中按键没有反应

### ISSUE THREAD

**Issue by greymanking** [zhouyuexie/vue-input-code#4]
使用Demo时，按数字键盘没有任何反应。没有进行深入研究，希望作者能解决这个问题，因为这个其他都非常切合我的要求。

**Comment by zhouyuexie** [comment]
@greymanking 能提供更多一点的详细信息吗?比如说手机系统,
chrome版本,键盘是哪种产商提供?

**Comment by greymanking** [comment]
安卓8.0，Chrome 67.0.3396.87，讯飞输入法

**Comment by zhouyuexie** [comment]
OK,我会尽快跟进测试.

**Comment by zhouyuexie** [comment]
@greymanking 已修复,最新版1.3.2可以正常使用.

**Comment by fiamma21** [comment]
微信内置浏览器首次加载没办法自动聚焦第一个input

**Comment by zhouyuexie** [comment]
> 微信内置浏览器首次加载没办法自动聚焦第一个input

这个描述是一个bug还是说需要增加一个feature?
还有这个issues已经close,有新的疑问可以新开一个issues讨论.
